# Resolution
MIN_RESOLUTION = 512
MIN_BORDERLINE_RES = 450
MAX_ALLOWED_RES = 1280

# Sharpness / blur
SHARPNESS_GOOD = 100.0
SHARPNESS_BORDERLINE = 80.0
SHARPNESS_SEVERE = 60.0

# Brightness
BRIGHTNESS_MIN_GOOD = 70
BRIGHTNESS_MIN_BORDERLINE = 50
BRIGHTNESS_MAX_GOOD = 190
BRIGHTNESS_MAX_BORDERLINE = 220

# Contrast
CONTRAST_MIN_GOOD = 35.0
CONTRAST_MIN_BORDERLINE = 25.0
CONTRAST_MAX_GOOD = 140.0
CONTRAST_MAX_BORDERLINE = 160.0

# Noise
NOISE_MAX_GOOD = 30.0
NOISE_MAX_BORDERLINE = 45.0
NOISE_SEVERE = 60.0

# Exposure
EXPOSURE_BORDERLINE_PCT = 20.0
EXPOSURE_SEVERE_PCT = 40.0

# Image formats
ALLOWED_FORMATS = {"JPEG", "PNG"}