# Resolution
MIN_RESOLUTION = 512
MIN_BORDERLINE_RES = 300
MAX_ALLOWED_RES = 1500  # lowered for Render free tier

# Sharpness / blur
SHARPNESS_GOOD = 100.0
SHARPNESS_BORDERLINE = 80.0
SHARPNESS_SEVERE = 60.0

# Brightness
BRIGHTNESS_MIN_GOOD = 80
BRIGHTNESS_MIN_BORDERLINE = 60
BRIGHTNESS_MAX_GOOD = 200
BRIGHTNESS_MAX_BORDERLINE = 220

# Contrast
CONTRAST_MIN_GOOD = 40.0
CONTRAST_MIN_BORDERLINE = 30.0
CONTRAST_MAX_GOOD = 120.0
CONTRAST_MAX_BORDERLINE = 140.0

# Noise
NOISE_MAX_GOOD = 25.0
NOISE_MAX_BORDERLINE = 35.0
NOISE_SEVERE = 45.0

# Exposure
EXPOSURE_BORDERLINE_PCT = 20.0
EXPOSURE_SEVERE_PCT = 40.0

# Image formats
ALLOWED_FORMATS = {"JPEG", "PNG"}